# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
    -   id: trailing-whitespace
    -   id: check-added-large-files
    -   id: check-json
    -   id: check-ast
    -   id: detect-private-key
    -   id: mixed-line-ending
    -   id: requirements-txt-fixer
    -   id: check-builtin-literals
#-   repo: https://github.com/pre-commit/mirrors-autopep8
#    rev: 'v1.6.0'
#    hooks:
#    -   id: autopep8
#-   repo: https://github.com/PyCQA/flake8
#    rev: 4.0.1
#    hooks:
#      - id: flake8
-   repo: https://github.com/kontrolilo/kontrolilo
    rev: v2.1.0
    hooks:
      - id: license-check-configuration-lint
      - id: license-check-pipenv
-   repo: https://github.com/Lucas-C/pre-commit-hooks-safety
    rev: v1.2.4
    hooks:
    -   id: python-safety-dependencies-check
#-   repo: https://github.com/psf/black
#    rev: 22.3.0
#    hooks:
#      - id: black
#-   repo: https://github.com/PyCQA/bandit
#    rev: 1.7.4
#    hooks:
#      - id: bandit
-   repo: local
    hooks:
      - id: custom-script-file
        name: build-docker-files
        entry: ./build-docker-directory.sh
        language: script