"""empty message

Revision ID: 2f83179d99e0
Revises: 546260eeabc5
Create Date: 2023-03-26 20:57:51.206934

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2f83179d99e0'
down_revision = '546260eeabc5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Channel', sa.Column('hubEnabled', sa.Boolean(), nullable=True))
    op.add_column('Channel', sa.Column('hubNSFW', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Channel', 'hubNSFW')
    op.drop_column('Channel', 'hubEnabled')
    # ### end Alembic commands ###
