"""empty message

Revision ID: 4d460df32dd8
Revises: 88c6c7db1c9d
Create Date: 2024-09-28 19:15:31.208251

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4d460df32dd8'
down_revision = '88c6c7db1c9d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Channel', sa.Column('channelBannerLocation', sa.String(length=255), nullable=True))
    op.add_column('user', sa.Column('bannerLocation', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'bannerLocation')
    op.drop_column('Channel', 'channelBannerLocation')
    # ### end Alembic commands ###
