"""empty message

Revision ID: 50bd4a968ad3
Revises: 2f83179d99e0
Create Date: 2023-12-02 08:52:36.593643

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '50bd4a968ad3'
down_revision = '2f83179d99e0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('settings', sa.Column('maxVideoUploadFileSize', sa.Integer(), nullable=True))
    op.add_column('settings', sa.Column('maxThumbnailUploadFileSize', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('settings', 'maxThumbnailUploadFileSize')
    op.drop_column('settings', 'maxVideoUploadFileSize')
    # ### end Alembic commands ###
