"""empty message

Revision ID: 546260eeabc5
Revises: d16a24635397
Create Date: 2023-02-06 03:24:16.088699

"""
from alembic import op
import sqlalchemy as sa
import flask_security

# revision identifiers, used by Alembic.
revision = '546260eeabc5'
down_revision = 'd16a24635397'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('role', sa.Column('permissions', flask_security.datastore.AsaList(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('role', 'permissions')
    # ### end Alembic commands ###
