"""empty message

Revision ID: d16a24635397
Revises: 6d1746989e64
Create Date: 2022-09-05 15:16:40.030538

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd16a24635397'
down_revision = '6d1746989e64'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('settings', sa.Column('webrtcPlaybackEnabled', sa.Boolean(), nullable=True))
    op.add_column('settings', sa.Column('webrtcSignalProtocol', sa.String(length=128), nullable=True))
    op.add_column('settings', sa.Column('webrtcSignalURL', sa.String(length=1024), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('settings', 'webrtcSignalURL')
    op.drop_column('settings', 'webrtcSignalProtocol')
    op.drop_column('settings', 'webrtcPlaybackEnabled')
    # ### end Alembic commands ###
