name: GitHubActionsBuilds

on: push

jobs:
  generate_version_number:
    runs-on: ubuntu-latest
    outputs:
      build_number: ${{ steps.buildnumber.outputs.build_number }}
    steps:
    - name: Generate build number
      id: buildnumber
      uses: einaregilsson/build-number@v3
      with:
        token: ${{secrets.github_token}}

  build_docker_osp-core:
    needs: generate_version_number
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: devedse
        password: ${{ secrets.DOCKERHUBTOKEN }}
    - name: Set up QEMU
      id: qemu
      uses: docker/setup-qemu-action@v1
      with:
        image: tonistiigi/binfmt:latest
        platforms: all
    - name: Available platforms
      run: echo ${{ steps.qemu.outputs.platforms }}
    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v1
    - name: Builder instance name
      run: echo ${{ steps.buildx.outputs.name }}
    - name: Available platforms
      run: echo ${{ steps.buildx.outputs.platforms }}
    - name: Run script file
      run: |
         chmod +x ./build-docker-directory.sh
         ./build-docker-directory.sh
      shell: bash
    - name: Run script file
      run: |
         find docker-build
      shell: bash
    - name: Tree123
      run: |
         find .
      shell: bash
    - name: Run Buildx osp-core
      run: |
        export VERSION=1.0.${{needs.generate_version_number.outputs.build_number}}
        echo Version: $VERSION
        docker buildx build -f docker-build/osp-core/Dockerfile --platform linux/arm64,linux/amd64 -t devedse/osp-core:${{needs.generate_version_number.outputs.build_number}} -t devedse/osp-core:latest ${{ github.ref == 'refs/heads/master' && '--push' || '' }} ./docker-build/osp-core

  build_docker_osp-rtmp:
    needs: generate_version_number
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: devedse
        password: ${{ secrets.DOCKERHUBTOKEN }}
    - name: Set up QEMU
      id: qemu
      uses: docker/setup-qemu-action@v1
      with:
        image: tonistiigi/binfmt:latest
        platforms: all
    - name: Available platforms
      run: echo ${{ steps.qemu.outputs.platforms }}
    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v1
    - name: Builder instance name
      run: echo ${{ steps.buildx.outputs.name }}
    - name: Available platforms
      run: echo ${{ steps.buildx.outputs.platforms }}
    - name: Run script file
      run: |
         chmod +x ./build-docker-directory.sh
         ./build-docker-directory.sh
      shell: bash
    - name: Run script file
      run: |
         find docker-build
      shell: bash
    - name: Tree123
      run: |
         find .
      shell: bash
    - name: Run Buildx osp-rtmp
      run: |
        export VERSION=1.0.${{needs.generate_version_number.outputs.build_number}}
        echo Version: $VERSION
        docker buildx build -f docker-build/osp-rtmp/Dockerfile --platform linux/arm64,linux/amd64 -t devedse/osp-rtmp:${{needs.generate_version_number.outputs.build_number}} -t devedse/osp-rtmp:latest ${{ github.ref == 'refs/heads/master' && '--push' || '' }} ./docker-build/osp-rtmp

  build_docker_osp-ejabberd:
    needs: generate_version_number
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: devedse
        password: ${{ secrets.DOCKERHUBTOKEN }}
    - name: Set up QEMU
      id: qemu
      uses: docker/setup-qemu-action@v1
      with:
        image: tonistiigi/binfmt:latest
        platforms: all
    - name: Available platforms
      run: echo ${{ steps.qemu.outputs.platforms }}
    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v1
    - name: Builder instance name
      run: echo ${{ steps.buildx.outputs.name }}
    - name: Available platforms
      run: echo ${{ steps.buildx.outputs.platforms }}
    - name: Run script file
      run: |
         chmod +x ./build-docker-directory.sh
         ./build-docker-directory.sh
      shell: bash
    - name: Run script file
      run: |
         find docker-build
      shell: bash
    - name: Tree123
      run: |
         find .
      shell: bash
    - name: Run Buildx osp-ejabberd
      run: |
        export VERSION=1.0.${{needs.generate_version_number.outputs.build_number}}
        echo Version: $VERSION
        docker buildx build -f docker-build/osp-ejabberd/Dockerfile --platform linux/arm64,linux/amd64 -t devedse/osp-ejabberd:${{needs.generate_version_number.outputs.build_number}} -t devedse/osp-ejabberd:latest ${{ github.ref == 'refs/heads/master' && '--push' || '' }} ./docker-build/osp-ejabberd